[[entity]]
    file = 'content/nature/apple-tree.toml'
    position = [-5, 0, -5]

[[entity]]
    file = 'content/tiles/tree.toml'
    position = [0, 0, -10]
[[entity]]
    file =  'content/tiles/tree.toml'
    position = [-10, 0, -6]
[[entity]]
    file =  'content/tiles/tree.toml'
    position = [-4, 0, 5]
[[entity]]
    file =  'content/tiles/tree.toml'
    position = [-10, 0, 9]
[[entity]]
    file =  'content/tiles/tree.toml'
    position = [-5, 0, 0]
[[entity]]
    file =  'content/tiles/tree.toml'
    position = [4, 0, 1]
[[entity]]
    file =  'content/tiles/tree.toml'
    position = [5, 0, -6]

[[entity]]
    file =  'content/tiles/wall.toml'
    position = [0, 0, 0]

[[entity]]
    file =  'content/tiles/wall.toml'
    position = [0, 0, 5]

[[entity]]
    file =  'content/tiles/wall.toml'
    position = [2.5, 0.0, 2.5]
    rotation = [0, 90, 0]

[[entity]]
    file =  'content/tiles/wall.toml'
    position = [-2.5, 0.0, 2.5]
    rotation = [0, 90, 0]

[[entity]]
    file =  'content/tiles/wall.toml'
    position = [0.0, 0.5, 0.0]
    rotation = [90, 0, 0]

[[entity]]
    file =  'content/tiles/wall.toml'
    position = [0.0, 0.5, 2.5]
    rotation = [90, 0, 0]

[[entity]]
    file = 'content/character/apple.toml'
    position = [-4.0, 2.2, 5.0]

[[entity]]
    def = 'enemy1'
    position = [-6.0, 0.0, 5.0]

[[entity]]
    def = 'friend1'
    position = [4.0, 0.5, 5.0]