[def.tree]
    file = 'content/tiles/tree.toml'

[def.wall]
    file = 'content/tiles/wall.toml'

[def.enemy1]
    file = 'content/character/enemy1.toml'

[[entity]]
    def = 'tree'
    position = [0, 0, -10]
[[entity]]
    def = 'tree'
    position = [-10, 0, -6]
[[entity]]
    def = 'tree'
    position = [-4, 0, 5]
[[entity]]
    def = 'tree'
    position = [-10, 0, 9]
[[entity]]
    def = 'tree'
    position = [-5, 0, 0]
[[entity]]
    def = 'tree'
    position = [4, 0, 1]
[[entity]]
    def = 'tree'
    position = [5, 0, -6]

[[entity]]
    def = 'wall'
    position = [0, 0, 0]

[[entity]]
    def = 'wall'
    position = [0, 0, 5]

[[entity]]
    def = 'wall'
    position = [2.5, 0.0, 2.5]
    rotation = [0, 90, 0]

[[entity]]
    def = 'wall'
    position = [-2.5, 0.0, 2.5]
    rotation = [0, 90, 0]

[[entity]]
    def = 'wall'
    position = [0.0, 0.5, 0.0]
    rotation = [90, 0, 0]

[[entity]]
    def = 'wall'
    position = [0.0, 0.5, 2.5]
    rotation = [90, 0, 0]

[[entity]]
    file = 'content/character/apple.toml'
    position = [-4.0, 2.2, 5.0]

[[entity]]
    def = 'enemy1'
    position = [-5.0, 0.0, 5.0]
