[has.player]
    is = 'content/character/sword.toml'
    position = [0, 5, 0]

[has.player.body]
    mass = 200
    size = [1, 1, 1]

[has.player.controller]
    turnSpeed =  5
    forwardSpeed = 2
    cameraLerp = 1
    cameraOffset = [5, 12, 5]
    cameraLookAt = [0, 0, 0]

[has.simple_floor]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]

[has.simple_floor2]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, 0, 5]

[has.simple_floor3]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, 0, -5]



[has.ambient_light.ambient]
    color = 16777215
    intensity = 0.9

[has.camera]
    camera = {}