[[vox]]
    file = 'tree'
    position = [0, 0, -10]
[[vox]]
    file = 'tree'
    position = [-10, 0, -6]
[[vox]]
    file = 'tree'
    position = [-4, 0, 5]
[[vox]]
    file = 'tree'
    position = [-10, 0, 9]
[[vox]]
    file = 'tree'
    position = [-5, 0, 0]
[[vox]]
    file = 'tree'
    position = [4, 0, 1]
[[vox]]
    file = 'tree'
    position = [5, 0, -6]

[[vox]]
    file = 'wall'
    position = [0, 0, 0]

[[vox]]
    file = 'wall'
    position = [0, 0, 5]

[[vox]]
    file = 'wall'
    position = [2.5, 0.0, 2.5]
    rotation = [0, 90, 0]

[[vox]]
    file = 'wall'
    position = [-2.5, 0.0, 2.5]
    rotation = [0, 90, 0]

[[vox]]
    file = 'wall'
    position = [0.0, 0.5, 0.0]
    rotation = [90, 0, 0]

[[vox]]
    file = 'wall'
    position = [0.0, 0.5, 2.5]
    rotation = [90, 0, 0]
