[has.floor]
    is = 'content/fallback/floor.toml'
    position = [0, 0, 0]

[has.placeholder]
    is = 'content/placeholder.toml'

[has.background]
    is = 'content/fallback/background.toml'
    position = [0, -10, -2]
    size = 0.9
    rotation = [0, 90, 0]

[has.another_floor]
    is = 'content/fallback/floor.toml'
    position = [-15, 0, 0]
