default = "idle"
size = 0.08
position = [1.5, 0.5, -0.4]
rotation = [0, 0, 25]

[animation.idle]
    speed = 100
    vox = [
        "characters/dinosaur/dino_1.vox",
        "characters/dinosaur/dino_2.vox",
    ]

