file = 'content/tiles/tree.toml'

[[child]]
    file = 'content/character/apple.toml'
    position = [1, 4, -1]
[[child]]
    file = 'content/character/apple.toml'
    position = [1, 4, -2]
    
[[child]]
    file = 'content/character/apple.toml'
    position = [1.5, 4.5, -1.0]