is = 'content/tiles/tree.toml'

[has.apple]
    is = 'content/character/apple.toml'
    position = [1, 4, -1]

[has.another_apple]
    is = 'content/character/apple.toml'
    position = [0, 0, 0]

[has.you_guessed_it_another_apple]
    is = 'content/character/apple.toml'
    position = [1.5, 4.5, -1.0]