[has.wall1]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, 0, 0]

[has.wall2]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, 0, -4]

[has.wall3]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, 0, 4]

[has.wall4]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [7, 0, 0]

[has.wall5]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [-7, 0, 0]

[has.wall6]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [7, 0, 4]

[has.wall7]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [-7, 0, 4]

[has.wall8]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [7, 0, -4]

[has.wall9]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [-7, 0, -4]
