[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, -1, 0]

[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, -1, -3]

[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, -1, 3]

[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [5, -1, 0]

[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [-5, -1, 0]

[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [5, -1, 3]

[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [-5, -1, 3]

[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [5, -1, -3]

[[child]]
    file = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [-5, -1, -3]
