[has.wall1]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, -1, 0]

[has.wall2]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, -1, -3]

[has.wall3]
    is = 'content/tiles/wall.toml'
    rotation = [90, 0, 0]
    position = [0, -1, 3]

[has.wall4]
    is = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [5, -1, 0]

[has.wall5]
    is = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [-5, -1, 0]

[has.wall6]
    is = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [5, -1, 3]

[has.wall7]
    is = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [-5, -1, 3]

[has.wall8]
    is = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [5, -1, -3]

[has.wall9]
    is = 'content/tiles/wall.toml'
    rotation = [90, -1, 0]
    position = [-5, -1, -3]
