type = 'Ranged'

#Weapon Details
[weapon]
name = 'Gravity Gun'
flavor_text = 'The Power of Z'
model = 'z_gun.vox'

#Technical Specifications

[attack_info]
attach_point = 'left hand'
ammo = 10
attack_template = 'vertical cylinder'
projectile_spawn_location = 10 #grids in front of you
bullet_size = [5, 10,50]
attack_radius = [5, 10, 50] # height and width 
can_move = true
can_charge = false
invulnerable_during = false
terrain_destructor = true
projectile_dmg = 50
collision_dmg = 0
velocity = 2 #meters per second? 

[effects]
particle_effect = 'gravity_Line'
sfx_on_use = true #with/without text to voice
sfx = 'Beyooooooooooo' #use gantz:0 soundbyte

#Timing
[timing] 
telegraph_time = 1 #1st step, time in seconds
attack_duration = 3