type = 'Thrown'

#Weapon Details
[weapon]
name = 'Frag Grenade'
flavor_text = 'Boom'
model = 'grenade.vox'

#Technical Specifications

[attack_info]
attach_point = 'left hand'
ammo = 1
attack_template = 'square'
projectile_spawn_location = 1 #grids in front of you
bullet_size = [0.3, 0.3, 0.3]
attack_radius = [5, 5, 5] # height and width
can_move = true
can_charge = true
invulnerable_during = false
terrain_destructor = true
projectile_dmg = 20
collision_dmg = 0
velocity = 2 #meters per second? 

[effects]
particle_effect = 'explosion'
sfx_on_use = true #with/without text to voice
sfx = 'Explosion' #use gantz:0 soundbyte

#Timing
[timing] 
telegraph_time = 0.5 #1st step, time in seconds
attack_duration = 1
travel_time = 3

