type = 'Ranged'

#Weapon Details
[weapon]
name = 'Healthy Ball'
flavor_text = 'It makes more sense in English'
model = ''

#Technical Specifications

[attack_info]
attach_point = 'left hand'
ammo = 1
attack_template = 'sphere'
projectile_spawn_location = 2 #grids in front of you
bullet_size = [10, 10, 10]
attack_radius = [100, 10, 50] # height and width 
can_move = false
can_charge = false
invulnerable_during = false
terrain_destructor = true
projectile_dmg = 500
collision_dmg = 500
velocity = 2 #meters per second? 

[effects]
particle_effect = 'spirit_Bomb'
sfx_on_use = true #with/without text to voice
sfx = 'Genki Damaaaaa' #use text to voice

#Timing
[timing] 
telegraph_time = 7 #1st step, time in seconds
attack_duration = 10
