# forward-axis movement
[[forward]]
    key="w"
    amount=1

[[forward]]
    key="s"
    amount=-1

[[forward]]
    gamepad="axis1"
    amount=-1

# right-axis movement
[[right]]
    key="d"
    amount=1

[[right]]
    key="a"
    amount=-1

[[right]]
    gamepad="axis0"
    amount=1

# up-axis movement
[[up]]
    key="x"
    amount=1

[[up]]
    key="c"
    amount=-1

# attack action
[[attack]]
    key=" "